In [1]:
import random
import numpy as np
import pandas as pd


dane = pd.read_csv('C:\\Users\\mateusz\\Desktop\\wyg.dane_aktywnosc.csv')
ramkadanych = pd.DataFrame(np.zeros(shape=(80,264)),
                             columns=dane['produktid'].unique(),
                             index=dane['klientid'].unique())
ramkadanych.head(15)
dane = dane.groupby(['klientid', 'produktid'])['zdarzenie'].sum().reset_index()
danedf = pd.DataFrame(dane, columns = ['klientid','produktid','zdarzenie'],dtype = int)
Ramkad = danedf.pivot(index = 'klientid', columns ='produktid', values = 'zdarzenie').fillna(0)
Ramkad.head(15)

kategorie = pd.read_csv('C:\\Users\\mateusz\\Desktop\\wyg.dane_kategorie.csv')
kategorie.head(15)
katvec = kategorie.values
katvec[1]
k1 = np.delete(katvec[1],0)
k2 = np.delete(katvec[2],0)


def create_reference_solution(chromosome_length):

    number_of_ones = int(chromosome_length / 2)

    # Build an array with an equal mix of zero and ones
    reference = np.zeros(chromosome_length)
    #reference[0: number_of_ones] = 1

    # Shuffle the array to mix the zeros and ones
    np.random.shuffle(reference)
    
    return reference

In [2]:
def create_starting_population(individuals, chromosome_length):
    # Set up an initial array of all zeros
    population = np.zeros((individuals, chromosome_length))
    
    # Loop through each row (individual)
    for i in range(individuals):
        # Choose a random number of ones to create
        ones = random.randint(0, chromosome_length)
        # Change the required number of zeros to ones
        population[i, 0:ones] = 1
        # Sfuffle row
        np.random.shuffle(population[i])
    
    return population

def create_starting_population2(individuals, chromosome_length):
    # Set up an initial array of all zeros
    population = np.zeros((individuals, chromosome_length))
    
    # Loop through each row (individual)
    for i in range(individuals):
        # Choose a random number of ones to create
        ones = random.randint(4, chromosome_length)
        # Change the required number of zeros to ones
        population[i, 0:ones] = 5
        # Sfuffle row
        np.random.shuffle(population[i])
    
    return population

In [5]:
ind1 =create_starting_population(10, 10)
#pop
#pop[1][1]
ind2 = create_starting_population(10, 10)

In [17]:
def iniPopWys(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] != 0].columns
    return targetUser
iniPopWys(Ramkad,12)

def initialPop(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] == 0].columns
    
    return targetUser

ram = initialPop(Ramkad,12)
ls1 = list(ram)
ls1 # wszystkie produkty na ktorych klient nie dokonal aktywnosci , zapisane w liscie
#teraz nalezy stworzyc N indywiduow , (dzielac liste na N(przyjalem =10) list)
x = range(20) 
l = np.array_split(np.array(ls1),20)  #jakos tak
l
print(l[0])
print(l[1])

[ 1  2  3  6 11 12 16 18 23 26 28 29 32]
[36 38 39 40 42 44 46 50 53 54 57 59 60]


In [23]:
import math
from sklearn.metrics import jaccard_similarity_score
from scipy.spatial import distance
from scipy.stats.stats import pearsonr
#proc3. KorelacjaZ
def KorelacjaZ(ind):
    korelacja = []
    
    for x in range(len(ind)-1):
        for y in range(len(ind)):       
            korelacja.append(jaccard_similarity_score(ind[x-1],ind[y]))
        
    return sum(korelacja)
print(KorelacjaZ(ind2))
print(KorelacjaZ(l))

50.000000000000014


ValueError: Found input variables with inconsistent numbers of samples: [12, 13]

In [7]:
def iniPopWys(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] != 0].columns
    return targetUser
iniPopWys(Ramkad,12)

def initialPop(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] == 0].columns
    
    return targetUser

ram = initialPop(Ramkad,12)
ls1 = list(ram)
ls1 # wszystkie produkty na ktorych klient nie dokonal aktywnosci , zapisane w liscie
#teraz nalezy stworzyc N indywiduow , (dzielac liste na N(przyjalem =10) list)
x = range(20) 
l = np.array_split(np.array(ls1),20)  #jakos tak
l
l[0]

array([ 1,  2,  3,  6, 11, 12, 16, 18, 23, 26, 28, 29, 32])

In [8]:
listoflists =[]
listoflists.append((l[:], l[0]))
l


[array([ 1,  2,  3,  6, 11, 12, 16, 18, 23, 26, 28, 29, 32]),
 array([36, 38, 39, 40, 42, 44, 46, 50, 53, 54, 57, 59, 60]),
 array([64, 67, 72, 74, 75, 81, 83, 84, 86, 89, 91, 92, 94]),
 array([ 97,  98,  99, 100, 102, 103, 104, 105, 106, 107, 110, 111, 112]),
 array([113, 117, 119, 121, 122, 123, 124, 126, 129, 130, 131, 132, 133]),
 array([134, 137, 140, 141, 143, 144, 145, 150, 152, 155, 156, 157, 158]),
 array([160, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 172, 173]),
 array([175, 176, 178, 180, 181, 182, 184, 186, 188, 189, 190, 192, 195]),
 array([196, 197, 200, 202, 203, 204, 211, 212, 217, 218, 220, 221, 222]),
 array([224, 225, 228, 229, 230, 231, 233, 236, 237, 238, 239, 240, 241]),
 array([244, 246, 248, 251, 252, 255, 256, 258, 259, 260, 261, 262, 263]),
 array([264, 269, 270, 274, 275, 277, 279, 280, 282, 284, 286, 289, 290]),
 array([294, 297, 298, 299, 300, 301, 303, 305, 306, 307, 310, 312, 313]),
 array([314, 317, 319, 321, 323, 324, 325, 327, 329, 330, 331, 3

In [9]:
def iniPopWys(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] != 0].columns
    return targetUser
iniPopWys(Ramkad,12)

def initialPop(rd,idklienta):
    targetUser = rd.loc[:,rd.loc[idklienta] == 0].columns
    
    return targetUser

In [11]:
AllUsers = []
for x in range(len(Ramkad.index)):    
    AllUsers.append(iniPopWys(Ramkad,x+1))

type(l[1])

numpy.ndarray

In [12]:
# l[1]

selectedU = []
for x in range(len(AllUsers)):
    result = np.in1d(AllUsers[x],l[0]).any()
    if result==True:
        selectedU.append(AllUsers[x])
print(l[0])
selectedU

[ 1  2  3  6 11 12 16 18 23 26 28 29 32]


[Int64Index([2, 72, 113, 145, 163, 176, 280, 305, 329, 330, 358, 364, 379, 447,
             470],
            dtype='int64', name='produktid'),
 Int64Index([6, 67, 164, 181, 260, 493], dtype='int64', name='produktid'),
 Int64Index([3, 107, 133, 196, 489], dtype='int64', name='produktid'),
 Int64Index([11, 12, 28, 126, 158, 297, 300, 303, 391], dtype='int64', name='produktid'),
 Int64Index([16, 18, 104, 107, 134, 144, 211, 248, 306, 381, 418, 442], dtype='int64', name='produktid'),
 Int64Index([ 23, 132, 156, 160, 178, 189, 222, 252, 277, 310, 340, 347, 405,
             431, 441, 445, 472, 492],
            dtype='int64', name='produktid'),
 Int64Index([12, 110, 200, 221], dtype='int64', name='produktid'),
 Int64Index([3, 176, 252, 263, 363], dtype='int64', name='produktid'),
 Int64Index([26, 228, 231], dtype='int64', name='produktid'),
 Int64Index([29, 356, 475], dtype='int64', name='produktid'),
 Int64Index([16, 39, 40, 121, 161, 453, 470], dtype='int64', name='produktid'),
 Int64In

In [25]:
targetUser = iniPopWys(Ramkad,3)

In [26]:
# proc 4.
import math
from sklearn.metrics import jaccard_similarity_score
from scipy.spatial import distance
from scipy.stats.stats import pearsonr

np.seterr(divide='ignore', invalid='ignore')
dane = pd.read_csv('C:\\Users\\mateusz\\Desktop\\wyg.dane_aktywnosc.csv')
dane = dane.groupby(['klientid', 'produktid'])['zdarzenie'].sum().reset_index()
ramkadanych = pd.DataFrame(np.zeros(shape=(80,264)),
                             columns=dane['produktid'].unique(),
                             index=dane['klientid'].unique())
danedf = pd.DataFrame(dane, columns = ['klientid','produktid','zdarzenie'],dtype = int)
Ramkad = danedf.pivot(index = 'klientid', columns ='produktid', values = 'zdarzenie').fillna(0)
Ramkad.head(15)
klienci1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
klienci2 = np.array([1,4,5,2,34,3,2,4,2,1])
def Podobienstwo(docelowy,wybranyKlient):
    normalizacja=[]
    for x in range(len(wybranyKlient)):
        u = wybranyKlient[x-1]
        w1 = np.corrcoef(docelowy,wybranyKlient)[0, 1]           
        w2 = jaccard_similarity_score(docelowy,u)[0][1] 
        norm = (w1*w2)
        normalizacja.append(norm)
        normalizacja = [0.0 if math.isnan(x) else x for x in normalizacja]
    return sum(normalizacja)

Podobienstwo(targetUser,selectedU)

ValueError: all the input array dimensions except for the concatenation axis must match exactly